parameters:
  jsonrpc_server.jms.handlers: []

services:
  jsonrpc_server.jms_adapter.view_listener:
    class: Bankiru\Api\JsonRpc\Adapters\JMS\SerializedJsonRpcResponseListener
    arguments:
    - "@jms_serializer"
    public: false
